# Generated by Django 4.1.3 on 2022-12-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
