# Generated by Django 4.1.3 on 2022-12-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shippingaddress_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
