# Generated by Django 4.1.5 on 2023-01-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_info_alter_shippingaddress_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress'),
        ),
    ]
