# Generated by Django 4.1.5 on 2023-01-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='info',
        ),
    ]
